version: "3.9"

services:
  traefik:
    image: traefik:v2.10  # 使用 Traefik 最新版本
    container_name: traefik
    restart: always
    ports:
      - "92:92"          # 将 Traefik 的 web 入口映射到宿主机的 92 端口
      - "8095:8095"      # 将 Traefik Dashboard 入口映射到宿主机的 8096 端口
      - "8075:8075"      # 爬虫api映射
      - "8076:8076"      # 作业提交api映射
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml  # 挂载静态配置文件
      - ./dynamic.yml:/etc/traefik/dynamic.yml  # 挂载动态配置文件
      - /var/run/docker.sock:/var/run/docker.sock  # 允许 Traefik 管理 Docker 容器
    
    networks:
     - traefik-net

networks:
  traefik-net:
    driver: bridge