version: "2.1"

services:
  
  ty_spider_server:
    build:
      context: .
      dockerfile: ./fastapi_server_file
    image: mini_py39_x64:1.14
    container_name: ty_spider_server
    working_dir: /my_codes
    privileged: true  # 将以特权模式运行
    # --- 在这里添加 pids_limit ---
    pids_limit: -1 # 设置为 -1 表示不限制，或者可以设置一个较大的值，例如 10240
    volumes:
      # - ./opt/project:/opt/project # 处理生成的group等文件
      # v100
      # - /public/home/surge/TYPHOON_PROJ/log/flood_ty_spider:/my_log # 日志
      # - /public/home/surge/TYPHOON_PROJ/nation_debt_flood/servers/microserver_tyspider:/my_codes
      # pc
      - /home/wam/my_logs/ty_spider:/my_log # 日志
      - /home/wam/my_proj/microserver_tyspider:/my_codes
    ports:
      - "8075:8075" # 爬虫api映射
    tty: true # 第一次上线测试时加入，去掉上面的 command，手动进入容器后方便查看问题
